"""init

Revision ID: 4e1add1cfd5d
Revises: 
Create Date: 2026-03-24 12:57:10.556565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e1add1cfd5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', postgresql.ENUM('DATACENTER', 'WORKSHOP', 'BUILDING', name='object_type_enum'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('ELECTRICITY', name='sensor_type_enum'), nullable=False),
    sa.Column('category', postgresql.ENUM('SERVERS', 'COOLING', 'UPS', 'LIGHTING', name='sensor_category_enum'), nullable=False),
    sa.Column('unit', sa.String(), server_default='кВт/ч', nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'sensor_id')
    )
    # ### end Alembic commands ###
    op.execute(
        "SELECT create_hypertable('readings'::regclass, 'time'::name, "
        "if_not_exists => TRUE);"
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    op.drop_table('sensors')
    op.drop_table('objects')
    # ### end Alembic commands ###
