"""init

Revision ID: 4e1add1cfd5d
Revises: 
Create Date: 2026-03-24 12:57:10.556565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e1add1cfd5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enums must match application models (lowercase values)
    object_type_enum = postgresql.ENUM('datacenter', 'workshop', 'building',
                                       name='object_type_enum', create_type=True)
    sensor_type_enum = postgresql.ENUM('electricity',
                                       name='sensor_type_enum', create_type=True)
    sensor_category_enum = postgresql.ENUM('servers', 'cooling', 'ups', 'lighting',
                                           name='sensor_category_enum', create_type=True)
    severity_level_enum = postgresql.ENUM('low', 'medium', 'high', 'critical',
                                          name='severity_level_enum', create_type=True)

    object_type_enum.create(op.get_bind(), checkfirst=True)
    sensor_type_enum.create(op.get_bind(), checkfirst=True)
    sensor_category_enum.create(op.get_bind(), checkfirst=True)
    severity_level_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        'objects',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', object_type_enum, nullable=False),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'sensors',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('object_id', sa.UUID(), nullable=False),
        sa.Column('type', sensor_type_enum, nullable=False),
        sa.Column('category', sensor_category_enum, nullable=False),
        sa.Column('unit', sa.String(), server_default='кВт/ч', nullable=False),
        sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'readings',
        sa.Column('time', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('sensor_id', sa.UUID(), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('time', 'sensor_id')
    )
    op.create_table(
        'anomalies',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('sensor_id', sa.UUID(), nullable=False),
        sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True),
                  server_default=sa.text('now()'), nullable=False),
        sa.Column('severity', severity_level_enum, nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('expected_value', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute(
        "SELECT create_hypertable('readings'::regclass, 'time'::name, "
        "if_not_exists => TRUE);"
        )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('anomalies')
    op.drop_table('readings')
    op.drop_table('sensors')
    op.drop_table('objects')
    op.execute("DROP TYPE IF EXISTS severity_level_enum")
    op.execute("DROP TYPE IF EXISTS sensor_category_enum")
    op.execute("DROP TYPE IF EXISTS sensor_type_enum")
    op.execute("DROP TYPE IF EXISTS object_type_enum")
